create table house (
    id int8 generated by default as identity,
    amount_of_rooms int4 not null,
    area int4 not null,
    deleted boolean not null,
    name varchar(255),
    user_name int8,
    primary key (id));

    create table roles (
        id int8 generated by default as identity,
         name varchar(255),
         primary key (id));

     create table users (
        id int8 generated by default as identity,
        email varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id));

   create table users_roles (
       user_id int8 not null,
        role_id int8 not null);

alter table if exists house add constraint house_user foreign key (user_name) references users;
alter table if exists users_roles add constraint roles_id foreign key (role_id) references roles;
alter table if exists users_roles add constraint users_id foreign key (user_id) references users;

